#!/bin/bash



# Automatic captions
# configure these options if you don't like the defaults 
#
textwidth=41 	 #you can wrap text for shorter lines
choplines=9 	 #need to chop off some html so html2text doesn't puke
languagecode=en  # set language code here, i use "en" for english


echo "$0" assumes you can just type -l in less to save the text you see.
echo ^
set -e 






vidcaptions () {
        youtube-dl   --write-auto-sub --sub-format ttml --skip-download  "$@"
}
cd /tmp
FIL=`tempfile`

rm $FIL
vidcaptions "$1" -o $FIL --sub-lang $languagecode  


tail -n+$choplines "$FIL"."$languagecode".ttml|  html2text -width $textwidth - |less 
echo 
echo type y now to remove tempfile
rm -iv "$FIL"."$languagecode".ttml #clean up /tmp


exit 0

